#!/usr/bin/env bash
# Installing HAproxy load balancer
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y install haproxy=2.6.\*
apt-get -y update

sed -i "/127.0.0.1 localhost/a 3.236.236.94 8871-lb-01\n44.211.31.180 8871-web-01\n44.210.77.98 8871-web-02" /etc/hosts
{
	echo -e "# HAproxy for web servers"
	echo -e "frontend web_frontend"
	echo -e "\tbind *:80"
	echo -e "\tmode http"
	echo -e "\toption h1-case-adjust-bogus-client"
	echo -e "\tdefault_backend web_backend"
	echo -e "\nbackend web_backend"
	echo -e "\tbalance roundrobin"
	echo -e "\tserver 11178-web-01 18.206.92.141:80 check"
	echo -e "\tserver 11178-web-02 44.192.79.41:80 check"
} >> /etc/haproxy/haproxy.cfg

sed -i "/daemon/a \\\th1-case-adjust x-served-by X-Served-By" /etc/haproxy/haproxy.cfg
service haproxy restart
