#!/usr/bin/env bash
# This script create the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

trap "echo I hate the kill command ; rm /var/run/myscript.pid ; exit" SIGTERM
trap "rm /var/run/myscript.pid ; exit" SIGQUIT
trap "echo Y U no love me?!" SIGINT

ps | pgrep bash | head -n 1 | awk '{print $1}' > /var/run/myscript.pid	# redirect pid

while true
do
	echo "To infinity and beyond"
	sleep 2
done
