#!/usr/bin/env bash
# This script manages manage_my_process.
# shellcheck disable=SC1091
. /lib/lsb/init-functions

function start()
{
    ./manage_my_process &
    echo $! > /var/run/my_process.pid # $! to get child pid
    echo "manage_my_process started"
}

function stop()
{
    kill -15 "$(cat /var/run/my_process.pid)"
    echo "manage_my_process stopped"
    rm /var/run/my_process.pid
}

function restart()
{
    kill -15 "$(cat /var/run/my_process.pid)" # kill child pid
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo $! > /var/run/my_process.pid # $! to get child pid
    echo "manage_my_process restarted"
}

case "$1" in
    "start" )
    start ;;
    "stop" )
    stop ;;
    "restart" )
    restart ;;
    * )
    echo "Usage: manage_my_process {start|stop|restart}" ;;
esac
