#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely.

trap "echo Terminated; exit" SIGTERM    # trap used to target signal and exit cleanly   
while true
do
    echo "To infinity and beyond"
    sleep 2
done
