#!/usr/bin/env bash
# This script displays number from 1-20, bad luck from China, bad luck from Japan, bad luck from Italy on displays 4, 9, 17

number=1

while [ "$number" -le "20" ]
do
    echo "$number"
    case $number in
        "4" )
            echo "bad luck from China" ;;
        "9" )
            echo "bad luck from Japan" ;;
        "17" )
            echo "bad luck from Italy" ;;
        * )
            ;;
    esac

    number=$(( number + 1 ))
done
