#!/usr/bin/env bash
# This script runs nginx as user
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80 /8080/' /etc/nginx/sites-available/default
pkill -9 apache
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
